---
- name: 'Installing packages'
  sudo: yes
  apt: pkg={{ item }}
  with_items:
    - ack-grep
    - silversearcher-ag
    - exuberant-ctags
    - git
    - gnupg
    - rbenv
    - ruby-build
    - tmux
    - tree
    - vim